export const allEvents = [ 
    {eName:"Panache", 
    eDesc:"At the runway showdown, students from diverse backgrounds compete fiercely, strutting with confidence to captivate the audience and judges.", 
    eTime:"TBA", 
    eDay:"Daily",
    eVenue:"Pandal",
    eType:"Register", 
    eRule:"https://docs.google.com/document/d/1pvjSEPHQi8cI_tFzj9ZV1_fAgLYLXSGf-e7xpfzEsAQ" ,
    eLink:"https://docs.google.com/forms/d/1-AsqBBHDRzm7qyZwLiJH82wVu1hZaRPi3Bu01cS9Kw4",
    category:"Main"},
        
    
    {eName:"Battle of the Bands", 
    eDesc:"Get ready for the ultimate clash of musical talent at the Battle of the Bands! College students armed with guitars, drums, and boundless energy will light up the stage with their unique sounds.", 
    eTime:"TBA", 
    eDay:"TBA",
    eVenue:"Pandal",
    eType:"Register", 
    eRule:"https://docs.google.com/document/d/19ujbhvh-RWhsT7PhAAA6LQ_MXHrPZQ-QrzX7reswLBQ/edit?usp=drive_link" ,
    eLink:"https://docs.google.com/forms/d/1edCZy1w6DyS7v489WJLtzP69cISXiF3OO39mW-g0zAs",
    category:"Music"},
    
    
    {eName:"Cultural Exibition", 
    eDesc:"A celebration of culture providing a lens into the diversity, heritage, and creativity of different cultures. Students exhibit artifacts, crafts, traditions, arts and customs that represent their cultural background.", 
    eTime:"10:00 - 16:00", 
    eDay:"Daily",
    eVenue:"On-campus Stalls",
    eType:"Register", 
    eRule: "https://drive.google.com/file/d/1v0E1Iln72s7U9Xod34bFEJVU6yF_lrcF/view?usp=drive_link", 
    eLink:"https://docs.google.com/forms/d/e/1FAIpQLSe_NLNNNQT0ZaLHKf82YRO-ujXWDJf9dVoqpw4yQjWqw_L_rg/viewform?usp=sf_link",
    category:"EBSB"},
    
    
    {eName:"Food Fest", 
    eDesc:"Savour the Flavour: Join us for a feast of delectable delights at the ultimate Food Fest - where taste meets tradition in every bite.", 
    eTime:"10:00 - 16:00", 
    eDay:"Daily",
    eVenue:"On-campus Stalls",
    eType:"Register", 
    eRule:"https://drive.google.com/file/d/1v0fw7EkJeM_g-q0QYhTrm9AhP1rhAjhw/view?usp=drive_link" , 
    eLink:"https://docs.google.com/forms/d/e/1FAIpQLSczwSLtkojjFykl5C_XUmaMMElk4SM44Y5vhmwfQUa_rzd4aA/viewform?usp=sf_link",
    category:"EBSB"},
    
    
    {eName:"Symphony", 
    eDesc:"Symphony is a Music competition event in singing and instrumental performances open to all students.  ", 
    eTime:"TBA", 
    eDay:"29th March",
    eVenue:"Pandal",
    eType:"Register", 
    eRule:"https://docs.google.com/document/d/19ujbhvh-RWhsT7PhAAA6LQ_MXHrPZQ-QrzX7reswLBQ" ,
    eLink:"https://docs.google.com/forms/d/1ZSGP6z1AXi25kNSmjBJxqYsSscIm3WD8pggKsplyyf0",
    category:"Music"},


    {eName:"Spic Macay", 
    eDesc:"Symphony is a Music competition event in singing and instrumental performances open to all students.  ", 
    eTime:"TBA", 
    eDay:"29th March",
    eVenue:"Pandal",
    eType:"Register", 
    eRule:"" ,
    eLink:"",
    category:"Music"},

    
    {eName:"Shimmer", 
    eDesc:"Freshers bring youthful energy and creativity to the stage, showcasing their individuality with nervous excitement. Dressed to impress in trendy outfits, they exude confidence, each aiming to leave a lasting impression.", 
    eTime:"TBA", 
    eType:"1st Years Only",
    eVenue:"TBA",
    eDay:"TBA",
    eRule:"https://drive.google.com/file/d/11Dkl8qWrK-T09EnJvXC8udV_23M7Mi4f/view?usp=drive_link" ,
    eLink:"",
    category:"Main"},

    {eName:"Open Mic", 
    eDesc:"Embark on a re-telling session of prose, poem, storytelling, stand-up comedy, jokes, quotes, their life journey, experiences, etc, along with the crowd for a light-hearted engaging experience", 
    eTime:"TBA", 
    eVenue:"Pandal",
    eDay:"TBA",
    eType:"Register", 
    eRule:"" ,
    eLink:"",
    category:"Literary"},


    {eName:"Extempore Speech", 
    eDesc:"Watch as challengers up to the take deliver impromptu speeches on randomized drawn topics within a limited timeframe & swiftly organize their thoughts, employing improvisational skills, coherence, and persuasion.", 
    eTime:"TBA", 
    eVenue:"Pandal",
    eDay:"TBA",
    eType:"Register", 
    eRule:"" ,
    eLink:"",
    category:"Literary"},

    
    {eName:"Treasure Hunt", 
    eDesc:"Let's hunt! Observe as teams decipher clues, solve puzzles, and navigate through various locations to find hidden treasures or objects by employing strategy, teamwork, and problem-solving skills to outwit opponents and locate the ultimate prize.", 
    eTime:"TBA", 
    eVenue:"Pandal",
    eDay:"TBA",
    eType:"Register", 
    eRule:"" ,
    eLink:"",
    category:"Literary"},


    {eName:"The Laughing Summit", 
    eDesc:"Get ready to embark on a laughter-filled journey as we bring you The Laughing Summit an electrifying evening of stand-up comedy tailored specifically for National Institute of Technology Meghalaya. ", 
    eTime:"TBA", 
    eVenue:"Pandal",
    eDay:"TBA",
    eType:"Register", 
    eRule:"" ,
    eLink:"",
    category:"TF"},


    {eName:"Flash Mob", 
    eDesc:"Get ready for a burst of spontaneous fun! Picture a lively public square filled with students coming together for an impromptu flashmob extravaganza! They'll showcase their talent through choreographed performances, all to kick off the most epic cultural fest of the year! ", 
    eTime:"TBA", 
    eVenue:"Pandal",
    eDay:"TBA",
    eType:"Register", 
    eRule:"" ,
    eLink:"",
    category:"DandD"},


    {eName:"Step Up Dance Competition", 
    eDesc:"Dancers can showcase their skills in solo, duo, trio, and group categories, covering everything from traditional to contemporary styles. Join us as students express themselves and compete against participants from colleges far and wide!", 
    eTime:"TBA", 
    eVenue:"Pandal",
    eDay:"TBA",
    eType:"Register", 
    eRule:"" ,
    eLink:"",
    category:"DandD"},


    {eName:"Prom Night", 
    eDesc:"It's a classy affair where students come together in stylish themed attire for an evening of elegance and celebration. From dancing to socializing, there's plenty of fun to be had as you create unforgettable memories with friends. ", 
    eTime:"TBA", 
    eVenue:"Pandal",
    eDay:"TBA",
    eType:"Register", 
    eRule:"" ,
    eLink:"",
    category:"DandD"},


    {eName:"Short Film", 
    eDesc:"Lights, camera, action! Dive into the world of short films where students from all departments and years come together to unleash their creativity! In just a brief span of time, we'll take you on a journey of storytelling, messages, and wild ideas. ", 
    eTime:"TBA", 
    eVenue:"Pandal",
    eDay:"TBA",
    eType:"Register", 
    eRule:"" ,
    eLink:"",
    category:"DandD"},


    {eName:"Drama Play", 
    eDesc:"Join us at NIT Meghalaya for an engaging drama performance! Our talented students bring to life captivating stories filled with emotions, conflicts, and relationships. Get ready to be moved and inspired as you witness their remarkable acting skills unfold on stage.", 
    eTime:"TBA", 
    eVenue:"Pandal",
    eDay:"TBA",
    eType:"Register", 
    eRule:"" ,
    eLink:"",
    category:"DandD"},


    {eName:"Tug of war", 
    eDesc:"", 
    eTime:"TBA", 
    eVenue:"Pandal",
    eDay:"TBA",
    eType:"Register", 
    eRule:"" ,
    eLink:"",
    category:"Krigg"},


    {eName:"Dumb Charades", 
    eDesc:"", 
    eTime:"TBA", 
    eVenue:"Pandal",
    eDay:"TBA",
    eType:"Register", 
    eRule:"" ,
    eLink:"",
    category:"Krigg"},


    {eName:"Musical Chair", 
    eDesc:"", 
    eTime:"TBA", 
    eVenue:"Pandal",
    eDay:"TBA",
    eType:"Register", 
    eRule:"" ,
    eLink:"",
    category:"Krigg"},


    {eName:"Rangoli", 
    eDesc:"", 
    eTime:"TBA", 
    eVenue:"Pandal",
    eDay:"TBA",
    eType:"Register", 
    eRule:"" ,
    eLink:"",
    category:"Krigg"},


    {eName:"Snakes and Ladders", 
    eDesc:"", 
    eTime:"TBA", 
    eVenue:"Pandal",
    eDay:"TBA",
    eType:"Register", 
    eRule:"" ,
    eLink:"",
    category:"Krigg"},

    
    {eName:"BGMI", 
    eDesc:"Compete in Battle Grounds Mobile India to claim the title of the best team!", 
    eTime:"TBA", 
    eVenue:"Online",
    eDay:"TBA",
    eType:"Register", 
    eRule:"https://drive.google.com/file/d/1c7Zd7B6dtAF94QE858pHnosOCQqOJRVK/view?usp=drive_link" , 
    eLink:"https://docs.google.com/forms/d/1NrAeFo95HouDi9QMxiW4b--AUPcSPT1htcTPcqIrA2E",
    category:"Gaming"},
    
    
    {eName:"Valorant", 
    eDesc:"Tactics, strategy, aim and teamwork. Show yours skills and your composure in the Squad-based Tactical Shooter Valorant.", 
    eTime:"TBA", 
    eVenue:"Online",
    eDay:"TBA",
    eType:"Register", 
    eRule:"https://drive.google.com/file/d/1uToud7TRkrAikPY4ADTjOs9prnfm3-nd/view?usp=drive_link" ,
    eLink:"https://docs.google.com/forms/d/1LAeVQh-WPL2qxJroKADj0ps8cuqM_Nn2VTE8Zbe7NX0",
    category:"Gaming"},

    
  ];