export const allEvents = [ 
    {eName:"Panache", 
    eDesc:"At the runway showdown, students from diverse backgrounds compete fiercely, strutting with confidence to captivate the audience and judges.", 
    eTime:"1:15 - 4:00 PM", 
    eDay:"6th April",
    eVenue:"Pandal",
    eType:"Register", 
    eRule:"https://drive.google.com/file/d/1YJkBImkehCgNy2Z11_howllaDVHTPLGO/view?usp=drive_link" ,
    eLink:"https://forms.gle/r88rteiCAf5RdYWW8",
    category:"Main",
    id:1},
        
    
    {eName:"Battle of the Bands", 
    eDesc:"Get ready for the ultimate clash of musical talent at the Battle of the Bands! College students armed with guitars, drums, and boundless energy will light up the stage with their unique sounds.", 
    eTime:"2:00 - 5:30 PM", 
    eDay:"4th April",
    eVenue:"Pandal",
    eType:"Register", 
    eRule:"https://drive.google.com/file/d/1fcnArac_Nw2Wc1uNMmHiSbkUvvhupqp_/view?usp=drive_link" ,
    eLink:"https://forms.gle/RsMGHoSEW1ZDNPmN8",
    category:"Music",
    id:2},
    
    
    {eName:"Cultural Exibition", 
    eDesc:"A celebration of culture providing a lens into the diversity, heritage, and creativity of different cultures. Students exhibit artifacts, crafts, traditions, arts and customs that represent their cultural background.", 
    eTime:"After Inauguration", 
    eDay:"4th April",
    eVenue:"On-campus Stalls",
    eType:"Register", 
    eRule: "https://drive.google.com/file/d/1i5BIk3qtS8HDsYJOGnlVLYONuwyOqwtb/view?usp=drive_link", 
    eLink:"https://docs.google.com/forms/d/e/1FAIpQLSe_NLNNNQT0ZaLHKf82YRO-ujXWDJf9dVoqpw4yQjWqw_L_rg/viewform?usp=sf_link",
    category:"EBSB",
    id:3},
    
    
    {eName:"Food Fest", 
    eDesc:"Savour the Flavour: Join us for a feast of delectable delights at the ultimate Food Fest - where taste meets tradition in every bite.", 
    eTime:"9:30AM - 3:30PM", 
    eDay:"5th April",
    eVenue:"On-campus Stalls",
    eType:"Register", 
    eRule:"https://drive.google.com/file/d/1YHnO2tS7B1D4Cc4JtXiUK1KsQw3jcQVb/view?usp=drive_link" , 
    eLink:"https://docs.google.com/forms/d/e/1FAIpQLSczwSLtkojjFykl5C_XUmaMMElk4SM44Y5vhmwfQUa_rzd4aA/viewform?usp=sf_link",
    category:"EBSB",
    id:4},
    
    
    {eName:"Symphony", 
    eDesc:"Get ready to be swept away by the melodies at Symphony, the ultimate music competition! Whether you're a solo sensation, part of a dynamic group, or showcasing your instrumental prowess.", 
    eTime:"8:30AM - 10:30AM", 
    eDay:"5th April",
    eVenue:"Pandal",
    eType:"Register", 
    eRule:"https://drive.google.com/file/d/16_uD0monX6FsaB2U29nNZ8WOSdTdo3Lc/view?usp=drive_link" ,
    eLink:"https://forms.gle/59qaQo2LAYpxiTMS7",
    category:"Music",
    id:5},


    {eName:"Spic Macay", 
    eDesc:"A celebration of Indian classical music, classical dance, folk music, yoga, meditation, crafts and other aspects of Indian culture", 
    eTime:"12:30 - 2:00 PM", 
    eDay:"4th April",
    eVenue:"Pandal",
    eType:"exhibition", 
    eRule:"" ,
    eLink:"",
    category:"Music",
    id:6},

    
    {eName:"Shimmer", 
    eDesc:"Freshers bring youthful energy and creativity to the stage, showcasing their individuality with nervous excitement. Dressed to impress in trendy outfits, they exude confidence, each aiming to leave a lasting impression.", 
    eTime:"1:30 - 2:30 PM", 
    eType:"Register",
    eVenue:"Pandal",
    eDay:"5th April",
    eRule:"https://drive.google.com/file/d/1lgIs8iLh2lrKEhAaeqWkKEEHOP3KNc-F/view?usp=drive_link" ,
    eLink:"",
    category:"Main",
    id:7},

    {eName:"Open Mic", 
    eDesc:"Embark on a re-telling session of prose, poem, storytelling, stand-up comedy, jokes, quotes, their life journey, experiences, etc, along with the crowd for a light-hearted engaging experience", 
    eTime:"9:30 - 10:30 AM", 
    eVenue:"Lecture Hall",
    eDay:"5th April",
    eType:"Register", 
    eRule:"https://drive.google.com/file/d/1dd_0aTlgb6ITWq_T7aYx3NVIKMDbjkSE/view?usp=drive_link" ,
    eLink:"https://forms.gle/vCrP3ne497VyQYZd9",
    category:"Literary",
    id:8},


    {eName:"Extempore Speech", 
    eDesc:"Watch as challengers up to the take deliver impromptu speeches on randomized drawn topics within a limited timeframe & swiftly organize their thoughts, employing improvisational skills, coherence, and persuasion.", 
    eTime:"1:00 - 2:00 PM", 
    eVenue:"CR5",
    eDay:"4th April",
    eType:"Register", 
    eRule:"https://drive.google.com/file/d/1VQYbzJZYhMdn6DGrYu_i8kuy5yQsHySq/view?usp=drive_link" ,
    eLink:"https://forms.gle/6ZEG7SkqkwErtqXa7",
    category:"Literary",
    id:9},

    
    {eName:"Treasure Hunt", 
    eDesc:"Let's hunt! Observe as teams decipher clues, solve puzzles, and navigate through various locations to find hidden treasures or objects by employing strategy, teamwork, and problem-solving skills to outwit opponents and locate the ultimate prize.", 
    eTime:"11:00AM - 3:00PM", 
    eVenue:"Lecture Hall",
    eDay:"5th April",
    eType:"Register", 
    eRule:"https://drive.google.com/file/d/1wexKxsSPYIWBlpE73Sx_SBAxaO5kkQ1P/view?usp=drive_link" ,
    eLink:"https://forms.gle/Wq5azh4V1y1rabN97",
    category:"Literary",
    id:10},


    // {eName:"The Laughing Summit", 
    // eDesc:"Get ready to embark on a laughter-filled journey as we bring you The Laughing Summit an electrifying evening of stand-up comedy tailored specifically for National Institute of Technology Meghalaya. ", 
    // eTime:"TBA", 
    // eVenue:"Pandal",
    // eDay:"TBA",
    // eType:"Register", 
    // eRule:"" ,
    // eLink:"",
    // category:"TF",
    // id:11},


    {eName:"Flash Mob", 
    eDesc:"Get ready for a burst of spontaneous fun! Picture a lively public square filled with students coming together for an impromptu flashmob extravaganza! They'll showcase their talent through choreographed performances, all to kick off the most epic cultural fest of the year! ", 
    eTime:"TBA", 
    eVenue:"TBA",
    eDay:"TBA",
    eType:"Register", 
    eRule:"" ,
    eLink:"",
    category:"DandD",
    id:12},


    {eName:"Step Up Dance Competition", 
    eDesc:"Dancers can showcase their skills in solo, duo, trio, and group categories, covering everything from traditional to contemporary styles. Join us as students express themselves and compete against participants from colleges far and wide!", 
    eTime:"TBA", 
    eVenue:"Pandal",
    eDay:"TBA",
    eType:"Register", 
    eRule:"https://drive.google.com/file/d/1UrbKVRcDZzxc4yLgOK_qs9awbD5YRqZx/view?usp=drive_link" ,
    eLink:"https://forms.gle/Ashkfb5PSimEXzZj9",
    category:"DandD",
    id:13},


    {eName:"Prom Night", 
    eDesc:"It's a classy affair where students come together in stylish themed attire for an evening of elegance and celebration. From dancing to socializing, there's plenty of fun to be had as you create unforgettable memories with friends. ", 
    eTime:"TBA", 
    eVenue:"Pandal",
    eDay:"TBA",
    eType:"Register", 
    eRule:"" ,
    eLink:"",
    category:"DandD",
    id:14},


    {eName:"Traditiional Dance", 
    eDesc:"Nothing is as beautiful as witnessing an indian traditional dance. A vibrant showcase of the rich cultural heritage of traditional dance.", 
    eTime:"10:30AM - 1:30PM", 
    eVenue:"Pandal",
    eDay:"5th April",
    eType:"Register", 
    eRule:"https://drive.google.com/file/d/1WWyfaSWyuRnjns--l7veQDxlrRLt0Jp8/view?usp=drive_link" ,
    eLink:"https://forms.gle/uPKWaqkg1VDoP7WM9",
    category:"DandD",
    id:27},


    {eName:"Short Film", 
    eDesc:"Lights, camera, action! Dive into the world of short films where students from all departments and years come together to unleash their creativity! In just a brief span of time, we'll take you on a journey of storytelling, messages, and wild ideas. ", 
    eTime:"TBA", 
    eVenue:"Pandal",
    eDay:"TBA",
    eType:"Register", 
    eRule:"" ,
    eLink:"",
    category:"DandD",
    id:15},


    {eName:"Drama Play", 
    eDesc:"Join us at NIT Meghalaya for an engaging drama performance! Our talented students bring to life captivating stories filled with emotions, conflicts, and relationships. Get ready to be moved and inspired as you witness their remarkable acting skills unfold on stage.", 
    eTime:"TBA", 
    eVenue:"Pandal",
    eDay:"TBA",
    eType:"Register", 
    eRule:"" ,
    eLink:"",
    category:"DandD",
    id:16},


    {eName:"Tug of war", 
    eDesc:"A battle of strength and cunning! Teams face each other in a bout of physical prowess in this fun competition", 
    eTime:"TBA", 
    eVenue:"TBA",
    eDay:"TBA",
    eType:"Register", 
    eRule:"https://docs.google.com/document/d/1w2-laZu84IZZ57UCpVlLtYlz-QanXm20" ,
    eLink:"https://forms.gle/MS64WpxLBiLY3rvy8",
    category:"Krigg",
    id:17},


    {eName:"Dumb Charades", 
    eDesc:"Is it a bird? Is it a plane? Perhaps its an engineering student trying their best to portray something without the ability to speak.", 
    eTime:"11:00AM - 3:00PM", 
    eVenue:"CR5",
    eDay:"5th April",
    eType:"Register", 
    eRule:"https://docs.google.com/document/d/198suwNzWLbaUi95vxzAkkq75LR55oA5e" ,
    eLink:"https://forms.gle/SAaPfg7PRzaEFeHY9",
    category:"Krigg",
    id:18},


    {eName:"Musical Chair", 
    eDesc:"To run, walk or sprint? Perhaps a steady pace and keen ear is required to secure a safe spot in the musical chair competion", 
    eTime:"9:30 - 11:30 AM", 
    eVenue:"Lecture Hall",
    eDay:"6th April",
    eType:"Register", 
    eRule:"https://drive.google.com/file/d/1xStq2xMSAvQLBbHQUNhUh3BIraBcIvIp" ,
    eLink:"https://forms.gle/5uxbHsDaBM5hBcax6",
    category:"Krigg",
    id:19},


    {eName:"Rangoli", 
    eDesc:"Rangoli, one of the most beautiful and most pleasing art forms of India, is comprised of two words, rang meaning color and aavalli meaning colored creepers or row of colors. ", 
    eTime:"TBA", 
    eVenue:"TBA",
    eDay:"TBA",
    eType:"Register", 
    eRule:"https://docs.google.com/document/d/1hmUNNeAct05VK355yKTa_dtXk7p59KMf" ,
    eLink:"https://forms.gle/PWuHHaVeMXaSxVZo9",
    category:"Krigg",
    id:20},


    {eName:"Snakes and Ladders", 
    eDesc:"A game of luck, tragedy, comedy, speed, snakes and ladders. Indulge in this childhood favourite game of many and enjoy the lighthearted fun of this classic game.", 
    eTime:"9:30AM - 12:30PM", 
    eVenue:"Mini Auditorium",
    eDay:"6th April",
    eType:"Register", 
    eRule:"https://drive.google.com/file/d/1TOgcaShVOaViSpsY0qJbhyrWv1sZH45w" ,
    eLink:"https://forms.gle/XFqFe2j2h9f67pkj9",
    category:"Krigg",
    id:21},


    {eName:"Photowalk", 
    eDesc:"A photowalk is an outdoor activity where individuals, often photographers, explore locations to capture creative images. ", 
    eTime:"TBA", 
    eVenue:"Mawranglang",
    eDay:"23rd Mar",
    eType:"Field Trip", 
    eRule:"" ,
    eLink:"",
    category:"Photography",
    id:24},


    {eName:"Face art", 
    eDesc:"At SHISHIR , neon face painting adds a glow to the festivities. Participants sport vibrant designs, creating a lively atmosphere of creativity and fun. ", 
    eTime:"All Day", 
    eVenue:"On-Campus Stalls",
    eDay:"5th April",
    eType:"FreeForAll", 
    eRule:"" ,
    eLink:"",
    category:"Photography",
    id:25},


    {eName:"Art and Craft", 
    eDesc:"The competition aims to foster creativity, innovation, and artistic expression among participants by providing them with limited materials to create unique artworks or crafts.", 
    eTime:"All Day", 
    eVenue:"On-Campus Stalls",
    eDay:"5th April",
    eType:"Register", 
    eRule:"https://drive.google.com/file/d/1tENzHxepUlNVsJp14nThcG8ji96V8-Xa/view?usp=drive_link" ,
    eLink:"https://forms.gle/dKQbvCdg1WjK86dV9",
    category:"Photography",
    id:26},


    {eName:"3D Live Drawing", 
    eDesc:"It involves using techniques and tools to represent objects in a 3 dimensional space while incorporating the artists unique style or preferences.", 
    eTime:"11:00AM - 12:00PM", 
    eVenue:"On-Campus Stalls",
    eDay:"6th April",
    eType:"Register", 
    eRule:"https://drive.google.com/file/d/140A9JZ4uklGLgQX8o-lOsop6mLBzRSGs/view?usp=drive_link" ,
    eLink:"https://docs.google.com/forms/d/1lXRLGlzSDNTdOnVJSsx103diKk0zy4-Vbrnt8Hs1F90/viewform?edit_requested=true",
    category:"Photography",
    id:27},

    
    {eName:"BGMI", 
    eDesc:"Compete in Battle Grounds Mobile India to claim the title of the best team!", 
    eTime:"TBA", 
    eVenue:"Online",
    eDay:"TBA",
    eType:"Register", 
    eRule:"https://drive.google.com/file/d/1i6zHnRJYQaBCPloETjRdgHGNHij4_Eel/view?usp=drive_link" , 
    eLink:"https://docs.google.com/forms/d/1NrAeFo95HouDi9QMxiW4b--AUPcSPT1htcTPcqIrA2E",
    category:"Gaming",
    id:22},
    
    
    {eName:"Valorant", 
    eDesc:"Tactics, strategy, aim and teamwork. Show yours skills and your composure in the Squad-based Tactical Shooter Valorant.", 
    eTime:"TBA", 
    eVenue:"Online",
    eDay:"TBA",
    eType:"Register", 
    eRule:"https://drive.google.com/file/d/1QFynuLqbpnEvrFqQ2v3O71J-UUPDeQxR/view?usp=drive_link" ,
    eLink:"https://docs.google.com/forms/d/1LAeVQh-WPL2qxJroKADj0ps8cuqM_Nn2VTE8Zbe7NX0",
    category:"Gaming",
    id:23},

    
  ];